### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by ddtch** [victordomingos/optimize-images-x#4]
Heelo I very want use this tool but can not figure out how to run this project on macOS, can you do a tutorial or so?

**Comment by victordomingos** [comment]
Hi! At this time we don't have a simple installer (but that would be cool), and no launcher is made available outside of the command-line shell. As it stands right now, it is required to have Python and its shell command `pip` on your system. You can use `pip` to install the most recent release from the PyPI repository:

```
python3.9 -m pip install optimize-images-x
```

It can be a good idea to keep this kind of Python apps isolated in their own virtual environments, so a useful tool is `pipx` (take a look at https://opensource.com/article/21/7/python-pipx). Instead of the command indicated above you could use this one:

```
pipx install optimize-images-x
```

After that, to run the application, just type `optimize-images-x` in the Terminal and press `Enter`.

It should also run ok in Python 3.10, but there is a nasty visual glitch related to tcl/tk that makes image buttons look bad, when using the `Aqua` theme.

**Comment by ddtch** [comment]
Thanks `pipx` kinda solve my problem; anyway, I didn't run GUI but could run images-optimize. But quality of pictures is getting very low (
Looking for different options to configure the compression process.

**Comment by victordomingos** [comment]
Please take a look at the command-line options for `optimize-images`. There are some examples in the [docs](https://github.com/victordomingos/optimize-images/blob/master/docs/docs_EN.md). For JPEG images you can set the quality level (a higher number means less image distortion).

The default settings are, well, what suited my original purpose of quickly compressing images for use in websites. I hope this tool can be useful for you.
